version: '3.3'
services:
  mongo:
    image: mongo
  app:
    build: .
    environment:
      WAIT_HOSTS: mongo:27017 
    ports:
      - '8085:8000'
      - '8085:8000'
      - '8090:8000'
    